set(UNIT_TEST_BASE_DIR ${CMAKE_BINARY_DIR}/unit_tests)
include_directories(${CMAKE_SOURCE_DIR}/src)
add_subdirectory(adsr_envelope_test)
add_subdirectory(all_pass_chain_test)
add_subdirectory(all_pass_filter_test)
add_subdirectory(application_service_test)
add_subdirectory(arpeggiator_test)
add_subdirectory(audio_file_io_test)
add_subdirectory(audio_scope_test)
add_subdirectory(auto_ducker_test)
add_subdirectory(auto_filter_test)
add_subdirectory(auto_note_off_offset_test)
add_subdirectory(auto_panner_test)
add_subdirectory(automation_service_test)
add_subdirectory(base_rate_source_test)
add_subdirectory(bass_grinder_test)
add_subdirectory(bass_synth_controller_test)
add_subdirectory(bass_synth_test)
add_subdirectory(cascaded_svf_test)
add_subdirectory(channel_strip_test)
add_subdirectory(clip_detector_test)
add_subdirectory(clipper_test)
add_subdirectory(column_settings_model_test)
add_subdirectory(compressor_test)
add_subdirectory(data_service_test)
add_subdirectory(dbtp_meter_test)
add_subdirectory(dc_blocker_test)
add_subdirectory(delay_line_test)
add_subdirectory(dimension_test)
add_subdirectory(early_reflections_test)
add_subdirectory(device_rack_controller_test)
add_subdirectory(device_service_test)
add_subdirectory(divide_down_generator_test)
add_subdirectory(drive_test)
add_subdirectory(drum_synth_controller_test)
add_subdirectory(drum_synth_test)
add_subdirectory(editor_service_test)
add_subdirectory(editor_service_undo_test)
add_subdirectory(effect_oversampling_test)
add_subdirectory(effect_rack_controller_test)
add_subdirectory(effect_rack_test)
add_subdirectory(effects_test)
add_subdirectory(event_selection_model_test)
add_subdirectory(example_song_test)
add_subdirectory(fader_test)
add_subdirectory(gain_test)
add_subdirectory(interpolator_test)
add_subdirectory(keyboard_service_test)
add_subdirectory(kick_808_test)
add_subdirectory(knob_controller_test)
add_subdirectory(level_meter_test)
add_subdirectory(lfo_test)
add_subdirectory(load_meter_test)
add_subdirectory(lufs_meter_test)
add_subdirectory(loudness_analyzer_test)
add_subdirectory(manual_service_test)
add_subdirectory(midi_cc_automations_model_test)
add_subdirectory(midi_cc_selection_model_test)
add_subdirectory(midi_exporter_test)
add_subdirectory(midi_importer_test)
add_subdirectory(midi_service_test)
add_subdirectory(midi_settings_model_test)
add_subdirectory(micro_pitch_shifter_test)
add_subdirectory(mixer_service_test)
add_subdirectory(modal_piano_string_test)
add_subdirectory(monitor_test)
add_subdirectory(multi_engine_test)
add_subdirectory(multiband_compressor_test)
add_subdirectory(note_column_line_container_helper_test)
add_subdirectory(note_column_model_handler_test)
add_subdirectory(note_column_model_test)
add_subdirectory(note_column_renderer_test)
add_subdirectory(note_converter_test)
add_subdirectory(panner_test)
add_subdirectory(phaser_test)
add_subdirectory(parallel_render_test)
add_subdirectory(parameter_mapper_test)
add_subdirectory(parameter_test)
add_subdirectory(ensemble_phaser_test)
add_subdirectory(piano_synth_test)
add_subdirectory(piano_synth_v2_test)
add_subdirectory(piano_synth_v3_test)
add_subdirectory(pitch_bend_automations_model_test)
add_subdirectory(play_order_test)
add_subdirectory(player_worker_test)
add_subdirectory(poly_blep_oscillator_test)
add_subdirectory(property_service_test)
add_subdirectory(real_time_worker_pool_test)
add_subdirectory(recent_files_model_test)
add_subdirectory(render_service_test)
add_subdirectory(render_settings_test)
add_subdirectory(rendering_test)
add_subdirectory(rta_test)
add_subdirectory(sampler_controller_test)
add_subdirectory(sampler_test)
add_subdirectory(saturating_svf_test)
add_subdirectory(selection_service_test)
add_subdirectory(settings_service_test)
add_subdirectory(side_chain_audio_test)
add_subdirectory(side_chain_service_test)
add_subdirectory(simple_eq_test)
add_subdirectory(song_overview_service_test)
add_subdirectory(song_test)
add_subdirectory(stereo_enhancer_test)
add_subdirectory(stereo_exciter_test)
add_subdirectory(stereo_field_meter_test)
add_subdirectory(stereo_field_renderer_test)
add_subdirectory(stereo_widener_test)
add_subdirectory(string_ensemble_test)
add_subdirectory(string_voice_test)
add_subdirectory(string_voice_v2_test)
add_subdirectory(synth_controller_test)
add_subdirectory(sub_mixer_test)
add_subdirectory(synth_test)
add_subdirectory(theme_service_test)
add_subdirectory(tip_service_test)
add_subdirectory(tube_stage_test)
add_subdirectory(track_settings_model_test)
add_subdirectory(true_stereo_panner_test)
add_subdirectory(upsampler_test)
add_subdirectory(air_band_eq_test)
add_subdirectory(analog_fuzz_test)
add_subdirectory(vintage_passive_eq_test)
add_subdirectory(waveguide_string_test)
add_subdirectory(wavetable_oscillator_test)
add_subdirectory(wavetable_test)
add_subdirectory(wavetable_synth_controller_test)
add_subdirectory(wave_designer_test)
add_subdirectory(wavetable_synth_test)
add_subdirectory(xml_serialization_test)
