#!/bin/bash

# Updates version in all build and packaging scripts. 
# Must be run in the project root.

VERSION_MAJOR=$1
VERSION_MINOR=$2
VERSION_PATCH=$3

DATE_ISO=$(date -u +%Y-%m-%d)

if [[ ! $1 || ! $2 || ! $3 ]]; then
    echo "Usage: $0 VERSION_MAJOR VERSION_MINOR VERSION_PATCH"
    exit 1
fi


FILE=CMakeLists.txt
echo "Updating ${FILE} .."
sed -i "s/^set(VERSION_MAJOR.*/set(VERSION_MAJOR ${VERSION_MAJOR})/" ${FILE} || exit 1
sed -i "s/^set(VERSION_MINOR.*/set(VERSION_MINOR ${VERSION_MINOR})/" ${FILE} || exit 1
sed -i "s/^set(VERSION_PATCH.*/set(VERSION_PATCH ${VERSION_PATCH})/" ${FILE} || exit 1

for FILE in scripts/build-archive; do
    echo "Updating ${FILE} .."
    sed -i -E "s/[0-9]+\.[0-9]+\.[0-9]+/$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH/g" ${FILE} || exit 1
done

APPDATA_FILE="data/linux/noteahead.appdata.xml"
if [[ -f $APPDATA_FILE ]]; then
    echo "Updating ${APPDATA_FILE} .."
    sed -i -E "s/(<release version=\")[^\"]*(\" date=\")[^\"]*(\")/\1${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}\2${DATE_ISO}\3/" "$APPDATA_FILE" || exit 1
else
    echo "Warning: ${APPDATA_FILE} does not exist, skipping."
fi

CHANGELOG="CHANGELOG"
if [[ -f $CHANGELOG ]]; then
    echo "Updating ${CHANGELOG} .."
    RFC_DATE=$(./scripts/rfc2822Time)
    VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"

    # Replace first x.y.z with version
    sed -i "0,/x.y.z/s/x.y.z/$VERSION/" "$CHANGELOG" || exit 1

    # Replace first "Release date:" with "Release date:\n\n$RFC_DATE"
    sed -i "0,/Release date:/s/Release date:/Release date:\n\n$RFC_DATE/" "$CHANGELOG" || exit 1

    # Prepend the new template
    printf "x.y.z\n=====\n\nRelease date:\n\nNew features:\n\nBug fixes:\n\nOther:\n\n" > "$CHANGELOG.new"
    cat "$CHANGELOG" >> "$CHANGELOG.new"
    mv "$CHANGELOG.new" "$CHANGELOG"
else
    echo "Warning: ${CHANGELOG} does not exist, skipping."
fi